name: Pull Request

on:
  pull_request:
    branches: [ "main" ]
    
jobs:
  pull-request-check:

    runs-on: ubuntu-latest

    steps:
    
    - name: setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
          
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: dotnet restore
      run: dotnet restore source/
      
    - name: dotnet build and test
      shell: pwsh
      run: |
        dotnet build --configuration Release --no-restore source/
        dotnet test source/
